//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RammyCube.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RammyCube.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Board {
            get {
                object obj = ResourceManager.GetObject("Board", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Boo {
            get {
                return ResourceManager.GetStream("Boo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream chimes {
            get {
                return ResourceManager.GetStream("chimes", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FGameBG {
            get {
                object obj = ResourceManager.GetObject("FGameBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FGameBG___עותק {
            get {
                object obj = ResourceManager.GetObject("FGameBG___עותק", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FGameBG_gif {
            get {
                object obj = ResourceManager.GetObject("FGameBG_gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FGameBG2 {
            get {
                object obj = ResourceManager.GetObject("FGameBG2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FGameBG3 {
            get {
                object obj = ResourceManager.GetObject("FGameBG3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FGameBG4 {
            get {
                object obj = ResourceManager.GetObject("FGameBG4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FWellcomeBG {
            get {
                object obj = ResourceManager.GetObject("FWellcomeBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JBlue {
            get {
                object obj = ResourceManager.GetObject("JBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JGreen {
            get {
                object obj = ResourceManager.GetObject("JGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JRed {
            get {
                object obj = ResourceManager.GetObject("JRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JYellow {
            get {
                object obj = ResourceManager.GetObject("JYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KlaliBG {
            get {
                object obj = ResourceManager.GetObject("KlaliBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KlaliBGwellcome {
            get {
                object obj = ResourceManager.GetObject("KlaliBGwellcome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MainBoard {
            get {
                object obj = ResourceManager.GetObject("MainBoard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MainBoard1 {
            get {
                object obj = ResourceManager.GetObject("MainBoard1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream notify {
            get {
                return ResourceManager.GetStream("notify", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Speech_Off {
            get {
                return ResourceManager.GetStream("Speech_Off", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Speech_On {
            get {
                return ResourceManager.GetStream("Speech_On", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tada {
            get {
                return ResourceManager.GetStream("tada", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Windows_Logoff_Sound {
            get {
                return ResourceManager.GetStream("Windows_Logoff_Sound", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Windows_Shutdown {
            get {
                return ResourceManager.GetStream("Windows_Shutdown", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap היום {
            get {
                object obj = ResourceManager.GetObject("היום", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap חדש_חדש {
            get {
                object obj = ResourceManager.GetObject("חדש_חדש", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap כפתור {
            get {
                object obj = ResourceManager.GetObject("כפתור", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap כפתור_סימתי {
            get {
                object obj = ResourceManager.GetObject("כפתור_סימתי", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
